ci: switch to newer linter action
https://github.com/golangci/golangci-lint-action/pull/1024
https://github.com/golangci/golangci-lint-action/releases/tag/v5.0.0

fixes various cache issues during the linter run,

  /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/CONTRIBUTORS: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/.gitattributes: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/pubsub/pub_test.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/pubsub/example_test.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/pubsub/mempubsub/example_test.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/pubsub/mempubsub/mem.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.37.0/pubsub/mempubsub/conformance_test.go: Cannot open: