tests: fix intermittent test failures with NATS server
The tests would fail intermittently locally and in the CI
because of the NATS server store directory being the same
across various packages. This sets up a temp store directory that
is cleaned up by the testing package for us.

--- FAIL: TestCreateReadUpdate (0.00s)
    nats_test.go:116:
        	Error Trace:	/home/runner/work/conditionorc/conditionorc/internal/store/nats_test.go:116
        	Error:      	Received unexpected error:
        	            	nats: error opening msg block file ["/tmp/nats/jetstream/$G/streams/KV_active-conditions/msgs/1.blk"]: open /tmp/nats/jetstream/$G/streams/KV_active-conditions/msgs/1.blk: no such file or directory
        	Test:       	TestCreateReadUpdate
--- FAIL: TestMultipleConditionUpdate (0.00s)
    --- FAIL: TestMultipleConditionUpdate/create_multiple_sanity_checks (0.00s)
        nats_test.go:175:
            	Error Trace:	/home/runner/work/conditionorc/conditionorc/internal/store/nats_test.go:175
            	Error:      	Received unexpected error:
            	            	nats: error opening msg block file ["/tmp/nats/jetstream/$G/streams/KV_active-conditions/msgs/1.blk"]: open /tmp/nats/jetstream/$G/streams/KV_active-conditions/msgs/1.blk: no such file or directory